# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_buscar_autor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Buscar_Autor(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 600)
        MainWindow.setStyleSheet("background-color: rgb(72, 145, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buscar_autor = QtWidgets.QLabel(self.centralwidget)
        self.buscar_autor.setGeometry(QtCore.QRect(380, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buscar_autor.setFont(font)
        self.buscar_autor.setObjectName("buscar_autor")
        self.nome_autor_2 = QtWidgets.QLabel(self.centralwidget)
        self.nome_autor_2.setGeometry(QtCore.QRect(60, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.nome_autor_2.setFont(font)
        self.nome_autor_2.setObjectName("nome_autor_2")
        self.input_nome_autor_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nome_autor_2.setGeometry(QtCore.QRect(210, 200, 461, 31))
        self.input_nome_autor_2.setObjectName("input_nome_autor_2")
        self.botao_buscar_autor = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_autor.setGeometry(QtCore.QRect(690, 190, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_buscar_autor.setFont(font)
        self.botao_buscar_autor.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_buscar_autor.setObjectName("botao_buscar_autor")
        self.codigo_autor_2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_autor_2.setGeometry(QtCore.QRect(60, 260, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_autor_2.setFont(font)
        self.codigo_autor_2.setObjectName("codigo_autor_2")
        self.input_codigo_autor_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_autor_2.setGeometry(QtCore.QRect(210, 260, 281, 31))
        self.input_codigo_autor_2.setObjectName("input_codigo_autor_2")
        self.botao_voltar_buscar_autor = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_buscar_autor.setGeometry(QtCore.QRect(400, 490, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_voltar_buscar_autor.setFont(font)
        self.botao_voltar_buscar_autor.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_voltar_buscar_autor.setObjectName("botao_voltar_buscar_autor")
        self.sistema_bibliotecario = QtWidgets.QLabel(self.centralwidget)
        self.sistema_bibliotecario.setGeometry(QtCore.QRect(290, 30, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sistema_bibliotecario.setFont(font)
        self.sistema_bibliotecario.setObjectName("sistema_bibliotecario")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buscar_autor.setText(_translate("MainWindow", "Buscar Autor"))
        self.nome_autor_2.setText(_translate("MainWindow", "Nome do autor:"))
        self.botao_buscar_autor.setText(_translate("MainWindow", "Buscar"))
        self.codigo_autor_2.setText(_translate("MainWindow", "Código do autor:"))
        self.botao_voltar_buscar_autor.setText(_translate("MainWindow", "Voltar"))
        self.sistema_bibliotecario.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Buscar_Autor()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
