# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_buscar_exemplar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Buscar_Exemplar(object):
    """
    classe que representa a tela de buscar livro pelo codigo.

    ...
    Atributes
    ----------
    resize : object
        dimensiona largura e altura da tela
    setStyleSheet : object
        estiliza a cor de fundo da tela
    setObjectName : object
        rotula algum lugar da tela, onde se deseja definir um nome ou frase curta
    setText :
        O método setText() da classe java.text.CollationElementIterator é usado para definir a nova string de origem para o objeto
    QLineEdit : object
        É um campo ou caixa de texto.
    QPushButton : object
        atribuem-se aos botoes de acoes da tela
    botao_buscar_exemplar :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para buscar um exemplar de livro pelo codigo.
    botao_voltar_busca_exemplar :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para voltar da tela buscar exemplar para a tela principal da biblioteca para usuarios.
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 656)
        MainWindow.setStyleSheet("background-color: rgb(72, 145, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buscar_exemplar = QtWidgets.QLabel(self.centralwidget)
        self.buscar_exemplar.setGeometry(QtCore.QRect(400, 80, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buscar_exemplar.setFont(font)
        self.buscar_exemplar.setObjectName("buscar_exemplar")
        self.codigo_exemplar2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_exemplar2.setGeometry(QtCore.QRect(70, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_exemplar2.setFont(font)
        self.codigo_exemplar2.setObjectName("codigo_exemplar2")
        self.input_codigo_exemplar2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_exemplar2.setGeometry(QtCore.QRect(250, 170, 271, 31))
        self.input_codigo_exemplar2.setObjectName("input_codigo_exemplar2")
        self.botao_buscar_exemplar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_exemplar.setGeometry(QtCore.QRect(580, 160, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_buscar_exemplar.setFont(font)
        self.botao_buscar_exemplar.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_buscar_exemplar.setObjectName("botao_buscar_exemplar")
        self.codigo_livro2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_livro2.setGeometry(QtCore.QRect(70, 250, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_livro2.setFont(font)
        self.codigo_livro2.setObjectName("codigo_livro2")
        self.input_codigo_livro2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_livro2.setGeometry(QtCore.QRect(250, 250, 271, 31))
        self.input_codigo_livro2.setObjectName("input_codigo_livro2")
        self.qtd_dias2 = QtWidgets.QLabel(self.centralwidget)
        self.qtd_dias2.setGeometry(QtCore.QRect(70, 320, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.qtd_dias2.setFont(font)
        self.qtd_dias2.setObjectName("qtd_dias2")
        self.input_qtd_dias2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_qtd_dias2.setGeometry(QtCore.QRect(370, 320, 221, 31))
        self.input_qtd_dias2.setObjectName("input_qtd_dias2")
        self.sistema_bibliotecario = QtWidgets.QLabel(self.centralwidget)
        self.sistema_bibliotecario.setGeometry(QtCore.QRect(320, 20, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sistema_bibliotecario.setFont(font)
        self.sistema_bibliotecario.setObjectName("sistema_bibliotecario")
        self.botao_voltar_busca_exemplar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_busca_exemplar.setGeometry(QtCore.QRect(420, 520, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_voltar_busca_exemplar.setFont(font)
        self.botao_voltar_busca_exemplar.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_voltar_busca_exemplar.setObjectName("botao_voltar_busca_exemplar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buscar_exemplar.setText(_translate("MainWindow", "Buscar exemplar"))
        self.codigo_exemplar2.setText(_translate("MainWindow", "Código do exemplar:"))
        self.botao_buscar_exemplar.setText(_translate("MainWindow", "Buscar"))
        self.codigo_livro2.setText(_translate("MainWindow", "Código do livro:"))
        self.qtd_dias2.setText(_translate("MainWindow", "Quantidade de dias para empréstimo:"))
        self.sistema_bibliotecario.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))
        self.botao_voltar_busca_exemplar.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Buscar_Exemplar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
