# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_buscar_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Buscar_Cadastro(object):
    """
    classe que representa a tela buscar cadastro de um usuario.

    ...
    Atributes
    ----------
    resize : object
        dimensiona largura e altura da tela
    setStyleSheet : object
        estiliza a cor de fundo da tela
    setObjectName : object
        rotula algum lugar da tela, onde se deseja definir um nome ou frase curta
    setText :
        O método setText() da classe java.text.CollationElementIterator é usado para definir a nova string de origem para o objeto
    QLineEdit : object
        É uma caixa de texto
    QPushButton : object
        atribuem-se aos botoes de acoes da tela
    botao_buscar_usuario :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para buscar cadasro de usuario do sistema
    boto_voltar_buscar :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para voltar da tela buscar usuario para a tela principal da bibblioteca para usuario.
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 689)
        MainWindow.setStyleSheet("background-color: rgb(72, 145, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buscar = QtWidgets.QLabel(self.centralwidget)
        self.buscar.setGeometry(QtCore.QRect(550, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buscar.setFont(font)
        self.buscar.setObjectName("buscar")
        self.codigo_usuario2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_usuario2.setGeometry(QtCore.QRect(250, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_usuario2.setFont(font)
        self.codigo_usuario2.setObjectName("codigo_usuario2")
        self.input_codigo_usuario2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_usuario2.setGeometry(QtCore.QRect(390, 120, 271, 31))
        self.input_codigo_usuario2.setObjectName("input_codigo_usuario2")
        self.botao_buscar_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_usuario.setGeometry(QtCore.QRect(720, 110, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_buscar_usuario.setFont(font)
        self.botao_buscar_usuario.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_buscar_usuario.setObjectName("botao_buscar_usuario")
        self.input_nome2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nome2.setGeometry(QtCore.QRect(120, 190, 571, 31))
        self.input_nome2.setObjectName("input_nome2")
        self.cpf2 = QtWidgets.QLabel(self.centralwidget)
        self.cpf2.setGeometry(QtCore.QRect(710, 190, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.cpf2.setFont(font)
        self.cpf2.setObjectName("cpf2")
        self.input_cpf2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cpf2.setGeometry(QtCore.QRect(760, 190, 221, 31))
        self.input_cpf2.setObjectName("input_cpf2")
        self.nome2 = QtWidgets.QLabel(self.centralwidget)
        self.nome2.setGeometry(QtCore.QRect(40, 200, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.nome2.setFont(font)
        self.nome2.setObjectName("nome2")
        self.fone2 = QtWidgets.QLabel(self.centralwidget)
        self.fone2.setGeometry(QtCore.QRect(40, 250, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.fone2.setFont(font)
        self.fone2.setObjectName("fone2")
        self.input_fone2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_fone2.setGeometry(QtCore.QRect(120, 250, 221, 31))
        self.input_fone2.setObjectName("input_fone2")
        self.endereco2 = QtWidgets.QLabel(self.centralwidget)
        self.endereco2.setGeometry(QtCore.QRect(360, 250, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.endereco2.setFont(font)
        self.endereco2.setObjectName("endereco2")
        self.input_endeco2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_endeco2.setGeometry(QtCore.QRect(450, 250, 571, 31))
        self.input_endeco2.setObjectName("input_endeco2")
        self.bairro2 = QtWidgets.QLabel(self.centralwidget)
        self.bairro2.setGeometry(QtCore.QRect(40, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.bairro2.setFont(font)
        self.bairro2.setObjectName("bairro2")
        self.input_bairro2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_bairro2.setGeometry(QtCore.QRect(120, 310, 371, 31))
        self.input_bairro2.setObjectName("input_bairro2")
        self.cidade2 = QtWidgets.QLabel(self.centralwidget)
        self.cidade2.setGeometry(QtCore.QRect(530, 310, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.cidade2.setFont(font)
        self.cidade2.setObjectName("cidade2")
        self.input_cidade2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cidade2.setGeometry(QtCore.QRect(610, 310, 371, 31))
        self.input_cidade2.setObjectName("input_cidade2")
        self.cep2 = QtWidgets.QLabel(self.centralwidget)
        self.cep2.setGeometry(QtCore.QRect(40, 360, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.cep2.setFont(font)
        self.cep2.setObjectName("cep2")
        self.input_cep2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cep2.setGeometry(QtCore.QRect(120, 360, 221, 31))
        self.input_cep2.setObjectName("input_cep2")
        self.email2 = QtWidgets.QLabel(self.centralwidget)
        self.email2.setGeometry(QtCore.QRect(360, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.email2.setFont(font)
        self.email2.setObjectName("email2")
        self.input_email2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_email2.setGeometry(QtCore.QRect(450, 360, 571, 31))
        self.input_email2.setObjectName("input_email2")
        self.senha2 = QtWidgets.QLabel(self.centralwidget)
        self.senha2.setGeometry(QtCore.QRect(40, 410, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.senha2.setFont(font)
        self.senha2.setObjectName("senha2")
        self.input_senha2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_senha2.setGeometry(QtCore.QRect(120, 410, 221, 31))
        self.input_senha2.setObjectName("input_senha2")
        self.boto_voltar_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.boto_voltar_buscar.setGeometry(QtCore.QRect(550, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.boto_voltar_buscar.setFont(font)
        self.boto_voltar_buscar.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.boto_voltar_buscar.setObjectName("boto_voltar_buscar")
        self.buscar_2 = QtWidgets.QLabel(self.centralwidget)
        self.buscar_2.setGeometry(QtCore.QRect(420, 10, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buscar_2.setFont(font)
        self.buscar_2.setObjectName("buscar_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buscar.setText(_translate("MainWindow", "Buscar Usuário"))
        self.codigo_usuario2.setText(_translate("MainWindow", "Código usuário:"))
        self.botao_buscar_usuario.setText(_translate("MainWindow", "Buscar"))
        self.cpf2.setText(_translate("MainWindow", "CPF:"))
        self.nome2.setText(_translate("MainWindow", "Nome:"))
        self.fone2.setText(_translate("MainWindow", "Telefone:"))
        self.endereco2.setText(_translate("MainWindow", "Endereço:"))
        self.bairro2.setText(_translate("MainWindow", "Bairro:"))
        self.cidade2.setText(_translate("MainWindow", "Cidade:"))
        self.cep2.setText(_translate("MainWindow", "CEP:"))
        self.email2.setText(_translate("MainWindow", "Email:"))
        self.senha2.setText(_translate("MainWindow", "Senha:"))
        self.boto_voltar_buscar.setText(_translate("MainWindow", "Voltar"))
        self.buscar_2.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Buscar_Cadastro()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
