# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_biblioteca_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Biblioteca_Usuario(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 639)
        MainWindow.setStyleSheet("background-color: rgb(72, 145, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bemvindo = QtWidgets.QLabel(self.centralwidget)
        self.bemvindo.setGeometry(QtCore.QRect(380, 10, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bemvindo.setFont(font)
        self.bemvindo.setObjectName("bemvindo")
        self.buscar = QtWidgets.QLabel(self.centralwidget)
        self.buscar.setGeometry(QtCore.QRect(470, 270, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buscar.setFont(font)
        self.buscar.setStyleSheet("color: rgb(0, 0, 127);")
        self.buscar.setObjectName("buscar")
        self.botao_voltar_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_biblioteca_usuario.setGeometry(QtCore.QRect(430, 550, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_voltar_biblioteca_usuario.setFont(font)
        self.botao_voltar_biblioteca_usuario.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_voltar_biblioteca_usuario.setObjectName("botao_voltar_biblioteca_usuario")
        self.botao_emprestimo_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_emprestimo_biblioteca_usuario.setGeometry(QtCore.QRect(180, 140, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_emprestimo_biblioteca_usuario.setFont(font)
        self.botao_emprestimo_biblioteca_usuario.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_emprestimo_biblioteca_usuario.setObjectName("botao_emprestimo_biblioteca_usuario")
        self.botao_devolucao_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_devolucao_biblioteca_usuario.setGeometry(QtCore.QRect(690, 140, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_devolucao_biblioteca_usuario.setFont(font)
        self.botao_devolucao_biblioteca_usuario.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_devolucao_biblioteca_usuario.setObjectName("botao_devolucao_biblioteca_usuario")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 250, 1001, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 520, 991, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.botao_buscar_emprestimo_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_emprestimo_biblioteca_usuario.setGeometry(QtCore.QRect(690, 340, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_buscar_emprestimo_biblioteca_usuario.setFont(font)
        self.botao_buscar_emprestimo_biblioteca_usuario.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.botao_buscar_emprestimo_biblioteca_usuario.setObjectName("botao_buscar_emprestimo_biblioteca_usuario")
        self.botao_buscar_devolucao_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_devolucao_biblioteca_usuario.setGeometry(QtCore.QRect(690, 440, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_buscar_devolucao_biblioteca_usuario.setFont(font)
        self.botao_buscar_devolucao_biblioteca_usuario.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.botao_buscar_devolucao_biblioteca_usuario.setObjectName("botao_buscar_devolucao_biblioteca_usuario")
        self.botao_buscar_livro_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_livro_biblioteca_usuario.setGeometry(QtCore.QRect(180, 340, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_buscar_livro_biblioteca_usuario.setFont(font)
        self.botao_buscar_livro_biblioteca_usuario.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.botao_buscar_livro_biblioteca_usuario.setObjectName("botao_buscar_livro_biblioteca_usuario")
        self.botao_buscar_exemplar_biblioteca_usuario = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_exemplar_biblioteca_usuario.setGeometry(QtCore.QRect(180, 440, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_buscar_exemplar_biblioteca_usuario.setFont(font)
        self.botao_buscar_exemplar_biblioteca_usuario.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.botao_buscar_exemplar_biblioteca_usuario.setObjectName("botao_buscar_exemplar_biblioteca_usuario")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bemvindo.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))
        self.buscar.setText(_translate("MainWindow", "Buscar"))
        self.botao_voltar_biblioteca_usuario.setText(_translate("MainWindow", "Voltar"))
        self.botao_emprestimo_biblioteca_usuario.setText(_translate("MainWindow", "Empréstimo"))
        self.botao_devolucao_biblioteca_usuario.setText(_translate("MainWindow", "Devolução"))
        self.botao_buscar_emprestimo_biblioteca_usuario.setText(_translate("MainWindow", "Empréstimo"))
        self.botao_buscar_devolucao_biblioteca_usuario.setText(_translate("MainWindow", "Devolução"))
        self.botao_buscar_livro_biblioteca_usuario.setText(_translate("MainWindow", "Livro"))
        self.botao_buscar_exemplar_biblioteca_usuario.setText(_translate("MainWindow", "Exemplar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Biblioteca_Usuario()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
