# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_autor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Autor(object):
    """
    classe que representa a tela para cadastrar um autor na base de dados do sistema, sendo essa funcionalidade especifica para usarios do tipo adiministrador.

    ...
    Atributes
    ----------
    resize : object
        dimensiona largura e altura da tela
    setStyleSheet : object
        estiliza a cor de fundo da tela
    setObjectName : object
        rotula algum lugar da tela, onde se deseja definir um nome ou frase curta
    setText :
        O método setText() da classe java.text.CollationElementIterator é usado para definir a nova string de origem para o objeto
    QLineEdit : object
        É um campo ou caixa de texto.
    QPushButton : object
        atribuem-se aos botoes de acoes da tela
    botao_cadastrar_autor :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para cadastrar um autor.
    botao_voltar_autor :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para voltar da tela autor para a tela principal da biblioteca para usuario administrador do sistema.
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 90, 135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cadastrar_autor = QtWidgets.QLabel(self.centralwidget)
        self.cadastrar_autor.setGeometry(QtCore.QRect(340, 100, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cadastrar_autor.setFont(font)
        self.cadastrar_autor.setObjectName("cadastrar_autor")
        self.nome_autor = QtWidgets.QLabel(self.centralwidget)
        self.nome_autor.setGeometry(QtCore.QRect(30, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.nome_autor.setFont(font)
        self.nome_autor.setObjectName("nome_autor")
        self.codigo_autor = QtWidgets.QLabel(self.centralwidget)
        self.codigo_autor.setGeometry(QtCore.QRect(30, 230, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_autor.setFont(font)
        self.codigo_autor.setObjectName("codigo_autor")
        self.input_nome_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nome_autor.setGeometry(QtCore.QRect(180, 170, 421, 31))
        self.input_nome_autor.setObjectName("input_nome_autor")
        self.input_codigo_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_autor.setGeometry(QtCore.QRect(180, 230, 281, 31))
        self.input_codigo_autor.setObjectName("input_codigo_autor")
        self.botao_cadastrar_autor = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar_autor.setGeometry(QtCore.QRect(650, 280, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_cadastrar_autor.setFont(font)
        self.botao_cadastrar_autor.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_cadastrar_autor.setObjectName("botao_cadastrar_autor")
        self.botao_voltar_autor = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_autor.setGeometry(QtCore.QRect(340, 490, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_voltar_autor.setFont(font)
        self.botao_voltar_autor.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_voltar_autor.setObjectName("botao_voltar_autor")
        self.sistema_bibliotecario = QtWidgets.QLabel(self.centralwidget)
        self.sistema_bibliotecario.setGeometry(QtCore.QRect(240, 20, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sistema_bibliotecario.setFont(font)
        self.sistema_bibliotecario.setObjectName("sistema_bibliotecario")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cadastrar_autor.setText(_translate("MainWindow", "Cadastrar autor"))
        self.nome_autor.setText(_translate("MainWindow", "Nome do autor:"))
        self.codigo_autor.setText(_translate("MainWindow", "Código do autor:"))
        self.botao_cadastrar_autor.setText(_translate("MainWindow", "Cadastrar"))
        self.botao_voltar_autor.setText(_translate("MainWindow", "Voltar"))
        self.sistema_bibliotecario.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Autor()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
