# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_biblioteca.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Biblioteca(object):
    """
    classe que representa a tela principal da biblioteca para o administrador do sistema, que contem os menus de acesso as funcionalidades do sistema bibliotecario para cadastrar dados referentes a autores, livros e seus respectivos exemplares.

    
    ...
    Atributes
    ----------
    resize : object
        dimensiona largura e altura da tela
    setStyleSheet : object
        estiliza a cor de fundo da tela
    setObjectName : object
        rotula algum lugar da tela, onde se deseja definir um nome ou frase curta
    setText :
        O método setText() da classe java.text.CollationElementIterator é usado para definir a nova string de origem para o objeto
    QPushButton : object
        atribuem-se aos botoes de acoes da tela
    botao_cadastrar_autor_biblioteca :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para cadastrar autor.
    botao_cadastrar_livro_biblioteca :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para cadastrar livro.
    botao_cadastrar_exemplar_biblioteca :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para cadastrar exemplar.
    botao_voltar_biblioteca_admin :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao de voltar da tela principal para a tela de login
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 703)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 90, 135);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sistema_bibliotecario = QtWidgets.QLabel(self.centralwidget)
        self.sistema_bibliotecario.setGeometry(QtCore.QRect(260, 20, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sistema_bibliotecario.setFont(font)
        self.sistema_bibliotecario.setObjectName("sistema_bibliotecario")
        self.cadastro = QtWidgets.QLabel(self.centralwidget)
        self.cadastro.setGeometry(QtCore.QRect(410, 90, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cadastro.setFont(font)
        self.cadastro.setObjectName("cadastro")
        self.botao_cadastrar_autor_biblioteca = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar_autor_biblioteca.setGeometry(QtCore.QRect(80, 270, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_cadastrar_autor_biblioteca.setFont(font)
        self.botao_cadastrar_autor_biblioteca.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_cadastrar_autor_biblioteca.setObjectName("botao_cadastrar_autor_biblioteca")
        self.botao_voltar_biblioteca_admin = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_biblioteca_admin.setGeometry(QtCore.QRect(380, 560, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_voltar_biblioteca_admin.setFont(font)
        self.botao_voltar_biblioteca_admin.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_voltar_biblioteca_admin.setObjectName("botao_voltar_biblioteca_admin")
        self.botao_cadastrar_livro_biblioteca = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar_livro_biblioteca.setGeometry(QtCore.QRect(380, 270, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_cadastrar_livro_biblioteca.setFont(font)
        self.botao_cadastrar_livro_biblioteca.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_cadastrar_livro_biblioteca.setObjectName("botao_cadastrar_livro_biblioteca")
        self.botao_cadastrar_exemplar_biblioteca = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar_exemplar_biblioteca.setGeometry(QtCore.QRect(670, 270, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.botao_cadastrar_exemplar_biblioteca.setFont(font)
        self.botao_cadastrar_exemplar_biblioteca.setStyleSheet("\n"
"background-color: rgb(134, 134, 100);")
        self.botao_cadastrar_exemplar_biblioteca.setObjectName("botao_cadastrar_exemplar_biblioteca")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sistema_bibliotecario.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))
        self.cadastro.setText(_translate("MainWindow", "Cadastro"))
        self.botao_cadastrar_autor_biblioteca.setText(_translate("MainWindow", "Autor"))
        self.botao_voltar_biblioteca_admin.setText(_translate("MainWindow", "Voltar"))
        self.botao_cadastrar_livro_biblioteca.setText(_translate("MainWindow", "Livro"))
        self.botao_cadastrar_exemplar_biblioteca.setText(_translate("MainWindow", "Exemplar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Biblioteca()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
