# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_buscar_devolucao.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Buscar_Devolucao(object):
    """
    classe que representa a tela de buscar devolucao de um emprestimo de exemplar de livro, atraves do codigo do exemplar e data da devolucao.

    ...
    Atributes
    ----------
    resize : object
        dimensiona largura e altura da tela
    setStyleSheet : object
        estiliza a cor de fundo da tela
    setObjectName : object
        rotula algum lugar da tela, onde se deseja definir um nome ou frase curta
    setText :
        O método setText() da classe java.text.CollationElementIterator é usado para definir a nova string de origem para o objeto
    QLineEdit : object
        É um campo ou caixa de texto.
    QPushButton : object
        atribuem-se aos botoes de acoes da tela
    botao_buscar_devolucao :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para buscar uma devolucao de emprestimo de exemplar, pelo codigo do exemplar e data da devolucao.
    botao_voltar_buscar_devolucao :
        elemento instanciado do QPushButton, que foi rotulado para identifica-lo como o botao para voltar da tela buscar devolucao de um emprestimo para a tela principal da biblioteca para usuarios.
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 621)
        MainWindow.setStyleSheet("background-color: rgb(72, 145, 218);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buscar_devolucao = QtWidgets.QLabel(self.centralwidget)
        self.buscar_devolucao.setGeometry(QtCore.QRect(420, 70, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buscar_devolucao.setFont(font)
        self.buscar_devolucao.setObjectName("buscar_devolucao")
        self.codigo_exemplar_2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_exemplar_2.setGeometry(QtCore.QRect(40, 160, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_exemplar_2.setFont(font)
        self.codigo_exemplar_2.setObjectName("codigo_exemplar_2")
        self.input_codigo_exemplar_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_exemplar_2.setGeometry(QtCore.QRect(220, 160, 271, 31))
        self.input_codigo_exemplar_2.setObjectName("input_codigo_exemplar_2")
        self.botao_buscar_devolucao = QtWidgets.QPushButton(self.centralwidget)
        self.botao_buscar_devolucao.setGeometry(QtCore.QRect(840, 210, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_buscar_devolucao.setFont(font)
        self.botao_buscar_devolucao.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_buscar_devolucao.setObjectName("botao_buscar_devolucao")
        self.data_devolucao_2 = QtWidgets.QLabel(self.centralwidget)
        self.data_devolucao_2.setGeometry(QtCore.QRect(540, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.data_devolucao_2.setFont(font)
        self.data_devolucao_2.setObjectName("data_devolucao_2")
        self.input_data_devolucao_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_data_devolucao_2.setGeometry(QtCore.QRect(710, 160, 271, 31))
        self.input_data_devolucao_2.setObjectName("input_data_devolucao_2")
        self.codigo_livro_2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_livro_2.setGeometry(QtCore.QRect(40, 330, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_livro_2.setFont(font)
        self.codigo_livro_2.setObjectName("codigo_livro_2")
        self.input_codigo_livro_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_livro_2.setGeometry(QtCore.QRect(220, 330, 271, 31))
        self.input_codigo_livro_2.setObjectName("input_codigo_livro_2")
        self.codigo_usuario_2 = QtWidgets.QLabel(self.centralwidget)
        self.codigo_usuario_2.setGeometry(QtCore.QRect(540, 330, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.codigo_usuario_2.setFont(font)
        self.codigo_usuario_2.setObjectName("codigo_usuario_2")
        self.input_codigo_usuario_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_codigo_usuario_2.setGeometry(QtCore.QRect(710, 330, 271, 31))
        self.input_codigo_usuario_2.setObjectName("input_codigo_usuario_2")
        self.botao_voltar_buscar_devolucao = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar_buscar_devolucao.setGeometry(QtCore.QRect(450, 520, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.botao_voltar_buscar_devolucao.setFont(font)
        self.botao_voltar_buscar_devolucao.setStyleSheet("background-color: rgb(134, 134, 100);")
        self.botao_voltar_buscar_devolucao.setObjectName("botao_voltar_buscar_devolucao")
        self.sistema_bibliotecario = QtWidgets.QLabel(self.centralwidget)
        self.sistema_bibliotecario.setGeometry(QtCore.QRect(350, 20, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.sistema_bibliotecario.setFont(font)
        self.sistema_bibliotecario.setObjectName("sistema_bibliotecario")
        self.data_emprestimo_2 = QtWidgets.QLabel(self.centralwidget)
        self.data_emprestimo_2.setGeometry(QtCore.QRect(40, 380, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.data_emprestimo_2.setFont(font)
        self.data_emprestimo_2.setObjectName("data_emprestimo_2")
        self.input_data_emprestimo_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_data_emprestimo_2.setGeometry(QtCore.QRect(220, 380, 271, 31))
        self.input_data_emprestimo_2.setObjectName("input_data_emprestimo_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buscar_devolucao.setText(_translate("MainWindow", "Buscar devolução"))
        self.codigo_exemplar_2.setText(_translate("MainWindow", "Código do exemplar:"))
        self.botao_buscar_devolucao.setText(_translate("MainWindow", "Buscar"))
        self.data_devolucao_2.setText(_translate("MainWindow", "Data da devolução:"))
        self.codigo_livro_2.setText(_translate("MainWindow", "Código do livro:"))
        self.codigo_usuario_2.setText(_translate("MainWindow", "Código Usuário:"))
        self.botao_voltar_buscar_devolucao.setText(_translate("MainWindow", "Voltar"))
        self.sistema_bibliotecario.setText(_translate("MainWindow", "SISTEMA BIBLIOTECÁRIO"))
        self.data_emprestimo_2.setText(_translate("MainWindow", "Data do empréstimo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Buscar_Devolucao()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
