# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './designer/tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Login.sizePolicy().hasHeightForWidth())
        Login.setSizePolicy(sizePolicy)
        Login.setMinimumSize(QtCore.QSize(400, 300))
        Login.setMaximumSize(QtCore.QSize(400, 300))
        qtRectangle = Login.frameGeometry()
        centerPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        Login.move(qtRectangle.topLeft())
        self.verticalLayoutWidget = QtWidgets.QWidget(Login)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 50, 261, 203))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imagem_livros = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.imagem_livros.setMinimumSize(QtCore.QSize(96, 96))
        self.imagem_livros.setMaximumSize(QtCore.QSize(96, 96))
        self.imagem_livros.setTextFormat(QtCore.Qt.AutoText)
        self.imagem_livros.setObjectName("imagem_livros")
        self.horizontalLayout_2.addWidget(self.imagem_livros)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.caixa_email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.caixa_email.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_email.setObjectName("caixa_email")
        self.verticalLayout.addWidget(self.caixa_email)
        self.caixa_senha = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.caixa_senha.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.caixa_senha.setObjectName("caixa_senha")
        self.verticalLayout.addWidget(self.caixa_senha)
        self.botao_login = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.botao_login.setObjectName("botao_login")
        self.verticalLayout.addWidget(self.botao_login)
        self.botao_fechar = QtWidgets.QPushButton(Login)
        self.botao_fechar.setObjectName(u"botao_fechar")
        self.botao_fechar.setGeometry(QtCore.QRect(340, 10, 50, 23))

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.caixa_email.setPlaceholderText(_translate("Login", "E-mail"))
        self.caixa_senha.setPlaceholderText(_translate("Login", "Senha"))
        self.botao_login.setText(_translate("Login", "Login"))
        self.botao_fechar.setText(_translate("Login", "Fechar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
