# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.resize(500, 300)
        Cadastro.setMinimumSize(QtCore.QSize(500, 300))
        Cadastro.setMaximumSize(QtCore.QSize(500, 300))
        qtRectangle = Cadastro.frameGeometry()
        centerPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        Cadastro.move(qtRectangle.topLeft())
        self.gridLayoutWidget = QtWidgets.QWidget(Cadastro)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.caixa_senha1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_senha1.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_senha1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.caixa_senha1.setObjectName("caixa_senha1")
        self.gridLayout.addWidget(self.caixa_senha1, 4, 0, 1, 1)
        self.caixa_endereco = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_endereco.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_endereco.setObjectName("caixa_endereco")
        self.gridLayout.addWidget(self.caixa_endereco, 0, 1, 1, 1)
        self.caixa_cpf = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_cpf.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_cpf.setObjectName("caixa_cpf")
        self.gridLayout.addWidget(self.caixa_cpf, 1, 0, 1, 1)
        self.caixa_senha2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_senha2.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_senha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.caixa_senha2.setObjectName("caixa_senha2")
        self.gridLayout.addWidget(self.caixa_senha2, 5, 0, 1, 1)
        self.caixa_email = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_email.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_email.setObjectName("caixa_email")
        self.gridLayout.addWidget(self.caixa_email, 3, 0, 1, 1)
        self.caixa_nome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_nome.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_nome.setObjectName("caixa_nome")
        self.gridLayout.addWidget(self.caixa_nome, 0, 0, 1, 1)
        self.caixa_telefone = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_telefone.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_telefone.setObjectName("caixa_telefone")
        self.gridLayout.addWidget(self.caixa_telefone, 2, 0, 1, 1)
        self.caixa_bairro = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_bairro.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_bairro.setObjectName("caixa_bairro")
        self.gridLayout.addWidget(self.caixa_bairro, 1, 1, 1, 1)
        self.caixa_cep = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.caixa_cep.setMinimumSize(QtCore.QSize(0, 30))
        self.caixa_cep.setObjectName("caixa_cep")
        self.gridLayout.addWidget(self.caixa_cep, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Cadastro)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 260, 481, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botao_voltar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.botao_voltar.setObjectName("botao_voltar")
        self.horizontalLayout.addWidget(self.botao_voltar)
        self.botao_confirmar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.botao_confirmar.setObjectName("botao_confirmar")
        self.horizontalLayout.addWidget(self.botao_confirmar)

        self.retranslateUi(Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)

    def retranslateUi(self, Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Cadastro.setWindowTitle(_translate("Cadastro", "Cadastro"))
        self.caixa_senha1.setPlaceholderText(_translate("Cadastro", "Senha"))
        self.caixa_endereco.setPlaceholderText(_translate("Cadastro", "Endereço"))
        self.caixa_cpf.setPlaceholderText(_translate("Cadastro", "CPF"))
        self.caixa_senha2.setPlaceholderText(_translate("Cadastro", "Repetir Senha"))
        self.caixa_email.setPlaceholderText(_translate("Cadastro", "E-mail"))
        self.caixa_nome.setPlaceholderText(_translate("Cadastro", "Nome"))
        self.caixa_telefone.setPlaceholderText(_translate("Cadastro", "Telefone"))
        self.caixa_bairro.setPlaceholderText(_translate("Cadastro", "Bairro"))
        self.caixa_cep.setPlaceholderText(_translate("Cadastro", "CEP"))
        self.botao_voltar.setText(_translate("Cadastro", "Voltar"))
        self.botao_confirmar.setText(_translate("Cadastro", "Confirmar Cadastro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastro = QtWidgets.QWidget()
    ui = Ui_Cadastro()
    ui.setupUi(Cadastro)
    Cadastro.show()
    sys.exit(app.exec_())
